### ISSUE TITLE
EXT-2 兄弟，有没有计划搞一个命令行版本？

### ISSUE THREAD

**Issue by Pillar1989** [JayHeng/NXP-MCUBootFlasher#10]

**Comment by JayHeng** [comment]
恩智浦官方提供的都是命令行工具，RT-Flash就是把恩智浦官方命令行工具包装一下，做一个符合初级用户习惯使用的GUI。你说的命令行版本具体有啥意义呢？

**Comment by Pillar1989** [comment]
@JayHeng  你说的是这个 https://github.com/JayHeng/NXP-MCUBootUtility
