### ISSUE TITLE
RTF-9 after USB-HID successful detection, an after selecting .sb file, why does it says at the bottom "Slot Green-'downloading...''s Blue - 'success'; Slot Red - 'Failure';

### ISSUE THREAD

**Issue by hule11** [JayHeng/NXP-MCUBootFlasher#17]
![image](https://user-images.githubusercontent.com/94568616/146595062-92bf4c00-140a-4b90-9ad4-99b64ea559bf.png)

**Comment by JayHeng** [comment]
It just show note about slot color, you can ignore the note
